#!/usr/bin/env python3

import os
import sys

import pika

def main():
    if len(sys.argv) < 2:
        print(f'usage: {sys.argv[0]} room')
        sys.exit(0)

    room = sys.argv[1]

    conn = pika.BlockingConnection(
        pika.ConnectionParameters(host='localhost'))

    ch = conn.channel()

    queue = ch.queue_declare(queue='', exclusive=True)
    queue_name = queue.method.queue
    #print(f'queue_name: {queue_name}')

    ch.queue_bind(
        exchange='i1-chat',
        queue=queue_name,
        routing_key=room)
        
    def callback(ch, method, properties, body):
        #print(f'{method}')
        #print(f'{properties}')
        username = properties.headers['username']
        say = body.decode('utf-8')
        print(f'{username}: {say}')

    ch.basic_consume(
        queue=queue_name,
        auto_ack=True,
        on_message_callback=callback)

    print(f'listening {room} queue')
    ch.start_consuming()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('interrupted')

        try:
            sys.exit(0)
        except SystemExit:
            os._exit(0)
