#!/usr/bin/env python3

import time
import stomp

class MyListener(stomp.ConnectionListener):
    def on_error(self, frame):
        print(f'on_error: {frame.body}')

    def on_message(self, frame):
        print(f'on_message: {frame.body}')


def main():
    conn = stomp.Connection([('127.0.0.1', 61613)])
    conn.set_listener('', MyListener())
    conn.connect(
        username='guest',
        password='guest',
        wait=True)

    conn.send(
        body='Hello room1 from STOMP!',
        destination='/exchange/i1-chat/room1')
        # headers={'routing-key': 'room1'})
    #time.sleep(.5)

    conn.disconnect()

if __name__ == '__main__':
    main()
